name: saasnutriologo
services:
- environment_slug: php
  github:
    branch: main
    deploy_on_push: true
    repo: JOSE-OMAR-FLORES/SaasNutriologo
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  routes:
  - path: /
  run_command: heroku-php-apache2 public/
  source_dir: /
  envs:
  - key: APP_NAME
    value: SaasNutriologo
  - key: APP_ENV
    value: production
  - key: APP_KEY
    value: ${APP_KEY}
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${_self.URL}
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: SESSION_DRIVER
    value: database
  - key: SESSION_LIFETIME
    value: "120"
  - key: CACHE_STORE
    value: database
  - key: QUEUE_CONNECTION
    value: database
  - key: MAIL_MAILER
    value: log

databases:
- engine: MYSQL
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "8"
